name: CI
on:
  push:
    branches:
      - main

jobs:
  docker:
    continue-on-error: true
    strategy:
      matrix:
        tag: ['34', '35', 'rawhide']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out code
        uses: actions/checkout@v2
      - name: Build Docker image
        uses: docker/build-push-action@v1
        with:
          dockerfile: Dockerfile
          build_args: TAG=${{ matrix.tag }}
          push: false 
